version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: miniproyecto_paralela
    volumes:
      - .:/usr/src/myapp
    working_dir: /usr/src/myapp
    entrypoint: ["./main.o"]